---
- name: installing the webserver
  hosts: prod
  become: yes
  tasks:
     - name: installing the httpd package
       yum:
         name: httpd
         state: latest
     - name: starting webservice
       service: 
         name: httpd
         state: started