---
- name: Demo on advanced loops
  hosts: prod
  become: yes
  gather_facts: no
  tasks:
     - name: Manage the rpm package
       yum:
         name: "{{item.name}}"
         state: "{{item.state}}"
       loop:
          - {name: 'httpd' , state: 'latest'}
          - {name: 'docker' , state: 'absent'}
          - {name: 'git' , state: 'absent'}
          - {name: 'nginx' , state: 'absent'}
        
     - name: starting webservice
       service: 
         name: httpd
         state: started